version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.3
jobs:
  cljs:
    docker:
      - image: cimg/clojure:1.12.6-openjdk-21.0-browsers
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          key: cljs-pnpm-{{ checksum "deps.edn" }}-{{ checksum "pnpm-lock.yaml" }}
      - run: node --version
      - run: sudo corepack enable || sudo npm i -g pnpm@11.21.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec shadow-cljs -v compile ci-tests
      - run: pnpm exec karma start --single-run
      - save_cache:
                paths:
                  - ~/.local/share/pnpm/store
                  - ~/.m2
                key: cljs-pnpm-{{ checksum "deps.edn" }}-{{ checksum "pnpm-lock.yaml" }}
  clj:
    docker: 
      - image: cimg/clojure:1.10.3
    steps:
      - checkout
      - restore_cache:
          key: clj-{{ checksum "deps.edn" }}
      - run: clojure -A:dev:tests:clj-tests
      - save_cache:
          paths:
            - ~/.m2
          key: clj-{{ checksum "deps.edn" }}
workflows:
  version: 2
  fullstack:
    jobs:
      - clj
      - cljs
